version: '3.8'
services:
  fastapi-app:
    image: fastapi-project:local
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi-project
    ports:
      - ${PORT}:8000
    restart: always
    env_file:
      - ${ENV}
    volumes:
      - ~/project_logs:/app/logs